overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -   type: attribute
                    dir: "%kernel.project_dir%/src/Entity"
                    suffix: ~
                -   type: attribute
                    dir: "%kernel.project_dir%/src/GraphQL"
                    suffix: ~

when@dev:
    overblog_graphiql:
        javascript_libraries:
            graphiql: "latest"
            react: "latest"
            fetch: "latest"
