#Editted
parameters:
    env(ORG_NAME): 'Kiwi'

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        menu: '@App\Template\MenuBuilder'
        personReg: '@App\Provider\Person\PersonRegistry'
        org: '%env(ORG_NAME)%'
        bunny: '@App\Provider\BunnyDataProvider'