#Editted
parameters:
    env(ORG_NAME): 'Kiwi'
    env(PROFILE_URL): ''    

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        menu: '@App\Template\MenuBuilder'
        org: '%env(ORG_NAME)%'
        oidc: '%env(OIDC_ADDRESS)%'
        profile_url: '%env(PROFILE_URL)%'