#Editted
parameters:
    env(ORG_NAME): 'Kiwi'
    env(PROFILE_URL): ''
    env(INSTALLED_VERSION): ''

twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '@App\Template\MenuBuilder'
        updater: '@App\Template\UpdateChecker'
        org: '%env(ORG_NAME)%'
        oidc: '%env(OIDC_ADDRESS)%'
        profile_url: '%env(PROFILE_URL)%'
        version: '%env(INSTALLED_VERSION)%'

when@test:
    twig:
        strict_variables: true
