#Editted
parameters:
    env(ORG_NAME): 'Kiwi'
    env(PROFILE_URL): ''    

twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '@App\Template\MenuBuilder'
        org: '%env(ORG_NAME)%'
        oidc: '%env(OIDC_ADDRESS)%'
        profile_url: '%env(PROFILE_URL)%'

when@test:
    twig:
        strict_variables: true
