vich_uploader:
    db_driver: orm

    mappings:
        activities:
            uri_prefix: /uploads/activities
            upload_destination: '%kernel.project_dir%/public/uploads/activities'
        claims:
           uri_prefix: /uploads/claims
           upload_destination: '%kernel.project_dir%/public/uploads/claims'
