tasks:
  - name: starting docker-compose
    init: |
      docker-compose up --build -d

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:  
  - name: Helpless-Kiwi
    description: Our access point to helpless-kiwi
    port: 8000
    visibility: private
    onOpen: notify
  - name: PhpMyAdmin
    description: Our access point to the database
    port: 8080
    visibility: private
    onOpen: notify
  - name: postgres
    description: Port for the database, we dont use this
    port: 3306
    visibility: private
    onOpen: ignore