version: '3.8'

services:
  database:
    image: mariadb:10.11
    container_name: kiwi_database-dev
    restart: on-failure
    environment:
      MARIADB_DATABASE: kiwi_dev
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kiwi_phpmyadmin-dev
    depends_on:
      - database
    restart: on-failure
    environment:
      PMA_HOST: database
    ports:
      - "8080:80"

  php:
    image: php:dev
    container_name: kiwi_symfony-dev
    depends_on:
      - database
    build:
      context: .
    restart: on-failure
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      SECURE_SCHEME: http
      DATABASE_URL: mysql://root:root@database/kiwi_dev
      ENV COMPOSER_ALLOW_SUPERUSER: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - .:/app:rw,cached
    ports:
      - "8000:8000"

volumes:
  db-data:
