#!/bin/bash

if [[ $1 == "--recurse" && $(git diff HEAD@{1}..HEAD@{0} -- ".hooks\\*" | wc -l) -gt 0 ]]; then
  if [ -x "$(which php)" ]; then
    echo -e ".hooks changed! Reinstalling .hooks"
    echo 
    php .hooks/install.php
  else
    echo -e ".hooks changed! Could not find php, please run php .hooks/install.php"
    echo -e "Continuing.."
    echo 
  fi
  .hooks/after-modif
  exit $?
fi

if [[ $(git diff HEAD@{1}..HEAD@{0} -- "composer.lock" "symfony.lock" | wc -l) -gt 0 ]]; then
  if [ -x "$(which composer)" ]; then
    echo -e "composer.lock changed! Running composer install"
    echo 
    composer install
  else
    echo -e "composer.lock changed! Could not find composer, please run composer install"
  fi
fi

if [[ $(git diff HEAD@{1}..HEAD@{0} -- "tailwind.config.js" "templates\\*" "assets\\*" | wc -l) -gt 0 ]]; then
  if [ -x "$(which php)" ]; then
    echo -e "templates changed! Running php bin/console tailwind:build"
    echo 
    php bin/console tailwind:build
  else
    echo -e "tailwind changed! Could not find php, please run php bin/console tailwind:build"
  fi
fi

exit 0