#!/bin/bash

LOGDIR="var/log/commits/"
mkdir -p "${LOGDIR}"

echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
PHP_CS_FIXER_LOG="phpcsfixer_output_`date +%s`.log"
HAS_PHP_CS_FIXER=false

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        $PHP_CS_FIXER fix --verbose "$line" >> "${LOGDIR}${PHP_CS_FIXER_LOG}" 2>&1;
        git add "$line";
    done
else
    echo ""
    echo "Please install php-cs-fixer, included in the composer file, e.g.:"
    echo ""
    echo "  composer install"
    echo ""
    echo "php-cs-fixer pre commit hook abort"
    exit 1
fi

echo "php-cs-fixer pre commit hook success"

exit 0
