name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'kiwi'
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: Validate composer.json and composer.lock
      run: composer validate --no-check-all --no-check-publish
      working-directory: kiwi
      continue-on-error: true
      
    - name: Move public for artifact building
      run: |
        egrep -lRZ 'public/' kiwi | xargs -0 -l sed -i -e 's/public\//..\/public_html\/kiwi\//g'
        sed -i -e 's/\/config\/bootstrap.php/\/..\/kiwi\/config\/bootstrap.php/g' kiwi/public/index.php
        sed -i -e 's/\"extra\": {/\"extra\": {\n        \"public-dir\": \"..\/public_html\/kiwi\",/g' kiwi/composer.json
        mkdir public_html
        mv kiwi/public public_html/kiwi
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev --optimize-autoloader
      working-directory: kiwi
      env:
        APP_DEBUG: 0
        APP_ENV: prod
  
    - name: Install JS dependencies
      run: yarn install
      working-directory: kiwi
    
    - name: Build JS dependencies
      run: yarn build
      working-directory: kiwi
     
    - name: Cleanup
      continue-on-error: true
      run: |
        rm kiwi/{,.[!.],..?}* 2> /dev/null
        rm -rf kiwi/.github
        rm -rf kiwi/.hooks
        rm -rf kiwi/assets
        rm -rf kiwi/bin
        rm -rf kiwi/node_modules
        rm -rf kiwi/var

    - name: Generate sample environment settings
      run: |
        touch kiwi/.env.local.php.sample
        cat > kiwi/.env.local.php.sample << EOL
        <?php
        return array (
            'APP_DEBUG' => '0',
            'APP_ENV' => 'prod',
            'APP_SECRET' => '6badc0fca270ab84a00a67226f9e2554',
            'USERPROVIDER_KEY' => 'ThisIsNotSoSecret',
            'DATABASE_URL' => 'mysql://db_user:db_pass@127.0.0.1:3306/db',
            'MAILER_URL' => 'null://localhost',
            'DEFAULT_FROM' => 'foo@bar.com',
        );
        EOL
      working-directory: kiwi
      
    - name: Save build
      uses: actions/upload-artifact@v1
      with:
        name: production
        path: .
       
