name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'kiwi'
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Composer Cache Directory
      id: composer-cache
      working-directory: kiwi
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
  
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('kiwi/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      working-directory: kiwi
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('kiwi/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Validate composer.json and composer.lock
      run: composer validate --no-check-all --no-check-publish
      working-directory: kiwi
      continue-on-error: true
      
    - name: Move public for artifact building
      if: github.ref == 'refs/heads/master'
      run: |
        egrep -lRZ 'public/' kiwi | xargs -0 -l sed -i -e 's/public\//..\/public_html\/kiwi\//g'
        sed -i -e 's/\/config\/bootstrap.php/\/..\/kiwi\/config\/bootstrap.php/g' kiwi/public/index.php
        sed -i -e 's/\"extra\": {/\"extra\": {\n        \"public-dir\": \"..\/public_html\/kiwi\",/g' kiwi/composer.json
        mkdir public_html
        mv kiwi/public public_html/kiwi
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev --optimize-autoloader
      working-directory: kiwi
      env:
        APP_DEBUG: 0
        APP_ENV: prod
  
    - name: Install JS dependencies
      run: yarn install
      working-directory: kiwi
    
    - name: Build JS dependencies
      run: yarn build
      working-directory: kiwi
     
    - name: Cleanup
      run: |
        rm kiwi/{,.[!.],..?}* 2> /dev/null || true
        rm -rf kiwi/.git
        rm -rf kiwi/.github
        rm -rf kiwi/.hooks
        rm -rf kiwi/assets
        rm -rf kiwi/bin
        rm -rf kiwi/node_modules
        rm -rf kiwi/var

    - name: Generate sample environment settings
      if: github.ref == 'refs/heads/master'
      run: |
        cat > kiwi/.env.local.php.sample << EOL
        <?php
        return array (
            'APP_DEBUG' => '0',
            'APP_ENV' => 'prod',
            'APP_SECRET' => '6badc0fca270ab84a00a67226f9e2554',
            'USERPROVIDER_KEY' => 'ThisIsNotSoSecret',
            'DATABASE_URL' => 'mysql://db_user:db_pass@127.0.0.1:3306/db',
            'MAILER_URL' => 'null://localhost',
            'DEFAULT_FROM' => 'foo@bar.com',
        );
        EOL
      
    - name: Save build
      uses: actions/upload-artifact@v1
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      with:
        name: prod
        path: .
       
