name: Testing

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.3', '8.4']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
      
    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: xdebug
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --optimize-autoloader
      env:
        APP_ENV: test
  
    - name: Build CSS dependencies
      run: php bin/console tailwind:build

    - name: Install CSS dependencies
      run: php bin/console asset-map:compile

    - name: Run linter
      run: composer lint

    - name: Run unit/functional tests
      run: composer test
